/home/ubuntu/anki-gpt-sync/requests.log {
    size 100M
    rotate 3
    maxage 30
    compress
    delaycompress
    missingok
    notifempty
    copytruncate
    create 0600 ubuntu ubuntu
    su ubuntu ubuntu
}
